---
apiVersion: v1
kind: Service
metadata:
  name: jumpserver-svc
  namespace: kube-system
  labels:
    app: jumpserver-svc
spec:
  ports:
    - port: 22
      name: ssh
      targetPort: 22
    - port: 80
      name: http
      targetPort: 80
  selector:
    app: "jumpserver"
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jumpserver
  namespace: kube-system
  labels:
    app: jumpserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jumpserver
  template:
    metadata:
      labels:
        app: jumpserver
    spec:
      #imagePullSecrets:
      #- name: regsecret
      containers:
      - name: jumpserver
        image: registry.cn-shenzhen.aliyuncs.com/infrastlabs/jumpserver:weak
        imagePullPolicy: Always
        # command: ['sh', '-c']
        # args:
        # - tail -f /dev/null
        ports:
        - containerPort: 22
        - containerPort: 80
      restartPolicy: Always
